### ISSUE TITLE
Have a fixed scale on axes while selecting particular clusters

### ISSUE THREAD

**Issue by ghost** [Dragonmasterx87/Interactive-3D-Plotting-in-Seurat-3.0.0#9]
Hi,
Thank you for developing this awesome tool!
I notice that when I choose what clusters to display on the UMAP, the scale on the axes changes accordingly. Is there a way to have a fixed scale? Thanks!

**Comment by Dragonmasterx87** [comment]
Hi @rtoddler thanks for using this and I'm glad you find it useful. So to answer your question, do you mean the multidimensional tSNE/UMAP coordinates? I don't think they can be changed because they are derived from factors extracted from the 3D tSNE/UMAP coordinates. also, they shouldn't be changed, because if you change the scale, that will greatly impact the overall distribution and shape of the clusters, basically you want to stay away fro that, even if your PI says elsewise. Hope that helps, if I am not understanding your question please let me know maybe I can help you achieve what you want.

**Comment by ghost** [comment]
Hi @Dragonmasterx87 Sorry I was not clear about my question. I emailed you an example of what I got. Please find more details in the email. I really appreciate your help!

**Comment by Dragonmasterx87** [comment]
@rtoddler  thanks for the challenge, I didn't reply to your email because I was trying to figure out how to do this. I will update the code to allow for this later as well. Here you go this should work:

```
# Before you plot, set the ranges of the axis you desire. This set axis range will be 
# present across all clusters, and plotly will not adjust for axis length anymore
# this axis length will persist even when selecting some clusters

# xaxis
axx <- list(
  nticks = 4,
  range = c(-10,10)
)

# yaxis
axy <- list(
  nticks = 4,
  range = c(-10,10)
)

#zaxis
axz <- list(
  nticks = 4,
  range = c(-10,10)
)

# Plot your data, in this example my Seurat object had 21 clusters (0-20)
fig <- plot_ly(data = plot.data, 
        x = ~UMAP_1, y = ~UMAP_2, z = ~UMAP_3, 
        color = ~seurat_clusters, 
        colors = c("lightseagreen",
                   "gray50",
                   "darkgreen",
                   "red4",
                   "red",
                   "turquoise4",
                   "black",
                   "yellow4",
                   "royalblue1",
                   "lightcyan3",
                   "peachpuff3",
                   "khaki3",
                   "gray20",
                   "orange2",
                   "royalblue4",
                   "yellow3",
                   "gray80",
                   "darkorchid1",
                   "lawngreen",
                   "plum2",
                   "darkmagenta"),
        type = "scatter3d", 
        mode = "markers", 
        marker = list(size = 5, width=2), # controls size of points
        text=~label, #This is that extra column we made earlier for which we will use for cell ID
        hoverinfo="text") #When you visualize your plotly object, hovering your mouse pointer over a point shows cell names

fig <- fig %>% layout(scene = list(xaxis=axx,yaxis=axy,zaxis=axz))
fig
```

Edit: for more on adjusting the axis in Plotly see [here](https://plotly.com/r/3d-axes/#range-of-axes)

**Comment by Dragonmasterx87** [comment]
@rtoddler please let me know if the solution works for you. Have a great day!

**Comment by ghost** [comment]
@Dragonmasterx87 Sweet! The code you provide help me to define the range for the axes. However, I realize that I was asking the wrong question lol 
It turns out that the range of the scale did not change but the "size" of the three axes. (It does not make sense to me why it was built in this way though.) I found a solution [here](https://community.plotly.com/t/creating-a-3d-scatterplot-with-equal-scale-along-all-axes/15108). 
I add **_aspectmode='cube'_** to the scene list of your code and it works!!
**_fig <- fig %>% layout(scene = list(xaxis=axx,yaxis=axy,zaxis=axz,aspectmode='cube'))_**
Thank you so much for the discussion. Have a wonderful day :)
